version: '3'
services:
  service_mongo:
    image: mongo:latest
    volumes:
      - mongo-vol:/data/db
    networks:
      - bdnetwork
  service_auth:
    image: autenticacao:0.1
    ports:
      - "1920:1920"
    networks:
      - bdnetwork
      - ftpnetwork
      - httpnetwork
    volumes:
      - ./logs:/logfile
  service_http:
    image: servidorhttp:0.1
    ports:
      - "1919:1919"
    networks:
      - httpnetwork
    volumes:
      - files-vol:/data/files
      - ./logs:/logfile
  service_ftp:
    image: servidorftp:0.1
    ports:
      - "21:21"
    networks:
      - ftpnetwork
    volumes:
      - files-vol:/volume
      - ./logs:/logfile
  service_web:
    image: webapp:0.1
    ports:
      - "8080:8080"
    networks:
      - httpnetwork
volumes:
  mongo-vol:
  files-vol:
networks:
  bdnetwork:
  ftpnetwork:
  httpnetwork:
