version: '3'
services:
  service1:
    image: mongo:latest
    volumes:
      - mongo-vol:/data/db
    networks:
      - bdnetwork
  service2:
    image: autenticacao:0.1
    networks:
      - bdnetwork
      - ftpnetwork
      - httpnetwork
    ports:
      - "1920:1920"
    volumes:
      - ./logs:/logfile
  service3:
    image: servidorhttp:0.1
    ports:
      - "1919:1919"
    networks:
      - httpnetwork
    volumes:
      - files-vol:/data/files
      - ./logs:/logfile
  service4:
    image: servidorftp:0.1
    ports:
      - "21:21"
    networks:
      - ftpnetwork
    volumes:
      - files-vol:/volume
      - ./logs:/logfile
  service6:
    image: webapp:0.1
    ports:
      - "8080:8080"
    networks:
      - httpnetwork
      - ftpnetwork
volumes:
  mongo-vol:
  files-vol:
networks:
  bdnetwork:
  ftpnetwork:
  httpnetwork:
