version: '3'
services:
  service_mongo:
    image: mongo:latest
    volumes:
      - mongo-vol:/data/db
    networks:
      - bdnetwork
  service_auth:
    image: auth:latest
    networks:
      - bdnetwork
      - ftpnetwork
      - httpnetwork
    volumes:
      - ./logs:/logfile
  service_http:
    image: http:latest
    networks:
      - httpnetwork
    volumes:
      - files-vol:/volume
      - ./logs:/logfile
  service_ftp:
    image: ftp:latest
    ports:
      - "21:21"
    networks:
      - ftpnetwork
    volumes:
      - files-vol:/volume
      - ./logs:/logfile
  service_proxy:
    image: proxy:latest
    ports:
      - "80:80"
    networks:
      - httpnetwork
  service_web:
    image: webapp:latest
    networks:
      - httpnetwork 
    volumes:
      - ./logs:/logfile
volumes:
  mongo-vol:
  files-vol:
networks:
  bdnetwork:
  ftpnetwork:
  httpnetwork:
